services:
  mongo:
    image: mongo:7
    container_name: inventisys-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./inventisys
      dockerfile: Dockerfile
    container_name: inventisys-backend
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/inventisys
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./front-inventisys
      dockerfile: Dockerfile
    container_name: inventisys-frontend
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  mongo_data:
