spring:
  application:
    name: inventisys
  data:
    mongodb:
      uri: mongodb://localhost:27017/inventisys
      database: inventisys

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000
